Set up basic structure
python-telegram-bot/ptbcontrib pull request #1
Opened 2020-10-17 21:12 UTC by Bibo-Joshi

Included  `extract_url` helpers as first contribution as template/show case

some remarks/discussion points/open questions:

* I feel like naming the package `ptb_contrib` but the repo `contrib` is inconsistent. Can we still change that?
* For now I put as copyright
    ```python
    # A library containing community-based extension for the python-telegram-bot library
    # Copyright (C) 2020
    # The ptb-contrib developers
    ```
* test setup is at a bare minimum. The bot that's provided has a fake token and can't be acutally used. I don't think that contributions will actually need to run valid tests with TG but can just monkeypatch everything. If they do need it at some point, we can re-add …
* `setup.py` current has
    ```python
          author_email='devs@python-telegram-bot.org',
          url='https://python-telegram-bot.org/',
    ```
    Or should that be changed?

2020-10-19 03:59 UTC, JosXa commented
Seems it's time to leave a #FIRST! 😜 With both first comment and first feature, haha



Good stuff. I'll have a look and review this week.

2020-10-27 18:32 UTC, Poolitzer requested changes
some slight changes

2020-10-28 17:06 UTC, Bibo-Joshi commented on .github/CONTRIBUTING.rst
> +.. _`Telegram group`: https://telegram.me/pythontelegrambotgroup
I'm not sure if opening another group just for ptbcontrib is worth it and it's not really off-topic. I guess having ptbcontrib questions in the on-topic group is not too bad. We can always change that, though …

2020-10-28 17:09 UTC, Bibo-Joshi commented on .github/CONTRIBUTING.rst
> +    def __init__(self, id, name, last_name=None, **kwargs):
True. I just removed the paragraph …

2020-10-28 17:11 UTC, Bibo-Joshi commented on README.rst
> +This library provides extensions for the `python-telegram-bot <https://python-telegram-bot.org>`_ library written and maintained by the community of PTB users.
Do we have multiple cumminities? o.0

2020-10-28 17:12 UTC, Bibo-Joshi commented on README.rst
> +    $ pip install "ptbcontrib[extension1,extension2] @ git+https://github.com/python-telegram-bot/ptbcontrib.git"
you think so? We could put `extract_urls` there, but I don't see a huge benefit. anyone who's not able to see that those are placeholders is probably not ready to use ptbcontrib …

2020-10-28 17:14 UTC, Bibo-Joshi commented on requirements-dev.txt
> +pylint
Well, `pre-commit` installs them on it's own, but if you want to run them manually, you need to have them installed. But, a few dev-reqs don't hurt too much, I guess. Switching yapf for black, though …

2020-10-28 17:15 UTC, Bibo-Joshi commented
Thanks for the comments @JosXa @Poolitzer :) Updated a bit and left some replies

2020-10-29 17:16 UTC, Poolitzer commented on .github/CONTRIBUTING.rst
> +.. _`Telegram group`: https://telegram.me/pythontelegrambotgroup
okay, lets see how it grows, we might want to outsource it then

2020-10-29 17:17 UTC, Poolitzer commented on README.rst
> +This library provides extensions for the `python-telegram-bot <https://python-telegram-bot.org>`_ library written and maintained by the community of PTB users.
potentially. This seems so narrowed down like you already have a defined one, and well, we dont :D

2020-10-29 17:17 UTC, Poolitzer commented on README.rst
> +    $ pip install "ptbcontrib[extension1,extension2] @ git+https://github.com/python-telegram-bot/ptbcontrib.git"
hm, okay, fair enough.

2020-10-29 17:18 UTC, Poolitzer commented on requirements-dev.txt
> +pylint
ha at least that

2020-10-29 17:18 UTC, Poolitzer reviewed
LGTM

2020-10-29 17:20 UTC, Bibo-Joshi commented on README.rst
> +This library provides extensions for the `python-telegram-bot <https://python-telegram-bot.org>`_ library written and maintained by the community of PTB users.
From my understanding "the community of PTB users" just means th set of all humans that use PTB. I don't see a benefit of differentiating between different subsets of that

2020-10-31 15:41 UTC, merged