Redis-based persistence
python-telegram-bot/ptbcontrib pull request #26
Opened 2021-08-03 09:05 UTC by schvv31n

Adds a `DictPersistence` subclass which uses Redis database to store data.

2021-08-08 18:41 UTC, Poolitzer requested changes
Hi!

First of all, thank you very much for your PR. Your code looks clean enough, and I know people use redis quite a lot, so having an easy interface for it will be appreciated. I went over your files and wrote together some suggestions.

Disclaimer, I have never used a redis database, so I might have misjudged something. Feel free to point that out to me.

2021-08-08 18:41 UTC, Poolitzer commented on ptbcontrib/redis_persistence/README.md
> +
indenting this section makes it into a codeblock, which is a bit weird imo.

2021-08-08 18:41 UTC, Poolitzer commented on ptbcontrib/redis_persistence/README.md
> +updater = telegram.ext.Updater(..., persistence = persistence, ...)
Putting spaces in function parameters is not correct according to PEP 8. Since those are code examples, having them up to standard would be great.

2021-08-08 18:41 UTC, Poolitzer commented on ptbcontrib/redis_persistence/README.md
> +updater = telegram.ext.Updater(..., persistence = RedisPersistence(db = db), ...)
same here.

2021-08-08 18:41 UTC, Poolitzer commented on ptbcontrib/redis_persistence/README.md
> +*   `redis-py`
Maybe pointing it to a mayor version ensure this code works even though redis updates and you aren't around updating the code? I dont know if that works well with redis, just a general recommendation.

2021-08-08 18:41 UTC, Poolitzer commented on ptbcontrib/redis_persistence/redispersistence.py
> +    Note: in the database, all keys created by this class are prefixed with 'ptb:'.
Usually we have the same setup with the args, so one new line and indenting.

Maybe you want to allow users to change the prefixes?
```suggestion
    Note: 
        In the database, all keys created by this class are prefixed with 'ptb:'.
```

2021-08-08 18:41 UTC, Poolitzer commented on ptbcontrib/redis_persistence/redispersistence.py
> +            Either this argument or 'url' must be specified.
I would really rename this to `database`. Sounds more professional. You can name your own variables how you want in your code imo, but user facing interfaces should be typed out.

2021-08-08 18:41 UTC, Poolitzer commented on ptbcontrib/redis_persistence/redispersistence.py
> +        db: :obj:`redis.Redis` - Connection to the Redis database.
same here 🙈

2021-08-08 18:41 UTC, Poolitzer commented on tests/test_redispersistence.py
> +#!/usr/bin/env python
Im not sure I like the design of this test. You don't check at all if it works with the pip library you rely on. And therefore you dont check if the url attribute works.

The TestPostgresPersistence test is way longer, maybe it makes sense to take inspiration from there? I understand tests that you take every use case you can have with your code and write a a check for it.

2021-08-08 18:41 UTC, Poolitzer commented on tests/test_redispersistence.py
> +            RedisPersistence()
I would also test that it works with only one db and url argument and not with both of them

2022-06-10 08:45 UTC, Bibo-Joshi commented
closing due to inactivity

2022-06-10 08:45 UTC, closed without merging