Timeout incompatibility
python-telegram-bot/ptbcontrib pull request #36
Opened 2021-11-12 03:36 UTC by l0rem

Since i couldn't come up with an actual fix i added a basic check.  Hopefully someone comes up with a way to recreate ConversationTimeoutCallbacks and process them correctly, but for now this should be fine.

2021-11-12 03:44 UTC, l0rem commented
Kinda-patch for Issue#35

2022-02-27 11:28 UTC, starry69 requested changes

2022-02-27 11:28 UTC, starry69 commented on ptbcontrib/ptb_sqlalchemy_jobstore/jobstore.py
> +                if isinstance(handler, ConversationHandler):
These two `if` statements can be joined with `and` also please fix `pre-commit`

2022-02-27 11:28 UTC, starry69 commented on ptbcontrib/ptb_sqlalchemy_jobstore/README.md
> +Current version does not support ConversationHandlers with active `conversation_timeout`.
Maybe rephrase it like;
ConversationHandler with `conversation_timeout` are not supported due to pickling limitations of threading related objects.

2022-06-10 08:46 UTC, Bibo-Joshi commented
closing due to inactivity

2022-06-10 08:46 UTC, closed without merging